openapi: 3.0.0
info:
  title: Express API with Swagger
  version: 1.0.0
  description: A sample API using Express and Swagger
servers:
  - url: http://localhost:3000
paths:
  /api/sample:
    get:
      summary: Get a sample resource
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Success message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"

    post:
      summary: Create a new sample resource
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SampleRequestBody"
      responses:
        "200":
          description: Success message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"

components:
  schemas:
    SuccessMessage:
      type: object
      properties:
        message:
          type: string
      example:
        message: "Sample resource message"

    SampleRequestBody:
      type: object
      properties:
        name:
          type: string
      example:
        name: John Doe
